//--- Author [ICE]
player createDiaryRecord["Diary", ["Bomba What News", "<br/>- More carefull placement items from constuction menu. Now impossible build something inside another building. But can build near with minimal distance.<br/>- Added ability to sell and buy supplies in central depot of any captured cities. Exchange rate demand from how much supplies get city.<br/>- The possibility to build a static defences in the town for any player. Static defences cost was decreased to 4 times
<br/>- Upgrade factory building protection:<br/>      Barracks upgrade level 0 and 1:  factory default protection (can be destroyed from ~1-2 SMAW shells)<br/>     Barracks upgrade level 2: protection up to x3 (can be destroyed from ~3-4 SMAW shells)<br/>      Barracks upgrade level 3: protection up to x5 (can be destroyed from ~5-6 SMAW shells)<br/>- Factory after 10 minutes from last attack begins autorepairing. Autorepair completed after 30 minutes from last attack. Repaired factory has 100% health<br/>- When side have factories, any player can buy heavy vehicles, light vehicles or solidiers in central depot of any captured city. Price increased to x3.<br/>"]];
player createDiaryRecord["Diary", ["Upgrades", "<br/>To be able to purchase higher levels of equipment or units, the factories need to be upgraded by the commander. The commander will need both cash and supply points to do this. He may ask for contributions from other team players to help out. Each factory has 3 levels."]];
player createDiaryRecord["Diary", ["Supplies", "<br/>Each captured town has an Actual and Potential Value. On the map you will see this represented as 2 numbers seperated by a / for example; Zelenogorsk, once captured will start as 30/120. This means that the current supplies to each player from this town is $30 per minute. Each time a supply truck arrives at the town depot its value will increase by 10. Remember though, the supply truck must be either fully loaded from the HQ or a Supply point or, have come from a town with a higher actual value. you will also receive 4 x the actual value as cash if you or one of your squad drives the truck. Supply runs should be the responsibility of all. The best way to win Warfare is to work together capping and then supping up the town before moving to another."]];
player createDiaryRecord["Diary", ["Building", "<br/>The commander builds a base. Each side starts with one Mobile Headqarters (MHQ). This is a vehicle the commander can use to build th headquarters (HQ) anywhere on the map. After the HQ is built, other buildings can be constructed. Only the commander can build factories and defenses around the base using the HQ. The HQ can also be packed up back as MHQ again and moved to another location."]];
player createDiaryRecord["Diary", ["Team", "<br/>All players and AI soldiers can buy subordinates, equipment and vehicles from the main base as well as some vehicles from the captured town forts. You can access all available facilities through the Purchase interface from inside the main base perimeter or anywhere on the map once a Command Center has been erected. Accessible supply factories are indicated by icons on right edge of the screen. If a Barracks has been built, select the Purchase Gear button to purchase weapons and ammunition. The equipment you purchase here will also be your starting kit when you respawn. In Purchase Units button, you will find a list of unit type icons along the top. Here you can buy empty or manned units from soldiers to aircraft."]];
player createDiaryRecord["Diary", ["Commander", "<br/>The Commander can be controlled either by player or by AI. He has access to extra resources and abilities: developing the base, setting objectives for teams, and defining the strategy of your side."]];
player createDiaryRecord["Diary", ["Voting", "<br/>After starting the warfare mission, you are confronted with the Vote Commander screen. Click on any name in the player list to cast your vote. If you join a game that has already started, you will not see the Vote Commander screen. A new vote for a new Commander can be started anytime using the Vote option in the Options interface. The commander assigns a mission and a role to a team leader, whether it be AI or human player. The role can include the type of equipment and vehicles the AI teams will use. Players have control of what they will use in their team. Mission is the task for the team to perform. You may disable the Commander Vote Pop-up in the Team Menu."]];
player createDiaryRecord["Diary", ["Summary", "<br/>Warfare is a blend of a team-based multiplayer mission and realtime strategy, where BLUFOR and OPFOR fight for the island control. Key objectives are to capture towns, defend your base and destroy the base of enemy. Both sides are lead by a commander, who influences his side's strategy. There are two kinds of resources: Supply points are used by the commander for building factories. Money is used to purchase weapons, units and vehicles."]];
player createDiaryRecord["Diary", ["LF Balance", "<br/> 
Unit  Cost  UpgradeLevel ChangedLoadout<br/>  
OPFOR<br/>
<br/>
BLUEFOR<br/>
Avenger 1200 2<br/>
Stryker_M2 1650 1<br/>
Stryker_Mk19 1950 1<br/>"]];
player createDiaryRecord["Diary", ["AF Balance", "<br/>ALL COMBAT JET AVAILABLE ONLY ON 3 LEVEL<br/> 
Unit  Cost  UpgradeLevel ChangedLoadout<br/>  
OPFOR<br/>
Ka52      29000  2  -8 vikhr, +8 ataka<br/>
Ka52Black 32000  3  -8 vikhr, +8 ataka, +2 R73<br/>
Su34 45000   3<br/>Su39 42400   3<br/>L39 27700  3<br/>su25takistan 42400 3<br/>An-2 7200  1  +4 FAB-250 +60 Flares<br/><br/>  BLUEFOR<br/>AH1Z 33000 2<br/>AH64D 30000 2<br/>F35 41500 2 -2GBU +2Mavericks<br/>A-10 42500 3<br/>AH1 Apache BAF 28500   2<br/>"]];
player createDiaryRecord["Diary", ["HF Balance", "<br/>Unit  Cost  UpgradeLevel ChangedLoadout <br/>  
OPFOR<br/><br/>
BLUEFOR<br/>
M6_Linebacker  6200 2  -8Stingers +8Sidewinders<br/>
Stryker_TOW 2650 0<br/>
Stryker_MGS 2950 0<br/>"]];