Private['_c','_u'];

_u = [];

/* WEST - Barracks */
if (WF_A2_Vanilla) then {
	_u 			= ['USMC_Soldier'];
	_u = _u		+ ['USMC_Soldier2'];
	_u = _u		+ ['USMC_Soldier_LAT'];
	_u = _u		+ ['USMC_Soldier_AT'];
	_u = _u		+ ['USMC_Soldier_HAT'];
	_u = _u		+ ['USMC_Soldier_AA'];
	_u = _u		+ ['USMC_Soldier_AR'];
	_u = _u		+ ['USMC_Soldier_MG'];
	_u = _u		+ ['USMC_Soldier_GL'];
	_u = _u		+ ['USMC_SoldierS_Sniper'];
	_u = _u		+ ['USMC_SoldierS_SniperH'];
	_u = _u		+ ['USMC_SoldierM_Marksman'];
	_u = _u		+ ['USMC_Soldier_Medic'];
	_u = _u		+ ['USMC_SoldierS_Engineer'];
	_u = _u		+ ['USMC_SoldierS'];
	_u = _u		+ ['USMC_SoldierS_Spotter'];
	_u = _u		+ ['USMC_Soldier_TL'];
	_u = _u		+ ['USMC_Soldier_SL'];
	_u = _u		+ ['USMC_Soldier_Crew'];
	_u = _u		+ ['USMC_Soldier_Pilot'];
	_u = _u		+ ['FR_GL'];
	_u = _u		+ ['FR_Corpsman'];
	_u = _u		+ ['FR_Assault_R'];
	_u = _u		+ ['FR_Assault_GL'];
	_u = _u		+ ['FR_AR'];
	_u = _u		+ ['FR_R'];
	_u = _u		+ ['FR_Sapper'];
	_u = _u		+ ['FR_AC'];
	_u = _u		+ ['FR_Marksman'];
};

if (WF_A2_Arrowhead) then {
	_u 			= ['US_Soldier_Light_EP1'];
	_u = _u		+ ['US_Soldier_EP1'];
	_u = _u		+ ['US_Soldier_B_EP1'];
	_u = _u		+ ['US_Soldier_LAT_EP1'];
	_u = _u		+ ['US_Soldier_AT_EP1'];
	_u = _u		+ ['US_Soldier_HAT_EP1'];
	_u = _u		+ ['US_Soldier_AA_EP1'];
	_u = _u		+ ['US_Soldier_AR_EP1'];
	_u = _u		+ ['US_Soldier_MG_EP1'];
	_u = _u		+ ['US_Soldier_GL_EP1'];
	_u = _u		+ ['US_Soldier_Sniper_EP1'];
	_u = _u		+ ['US_Soldier_SniperH_EP1'];
	_u = _u		+ ['US_Soldier_Sniper_NV_EP1'];
	_u = _u		+ ['US_Soldier_Marksman_EP1'];
	_u = _u		+ ['US_Soldier_Medic_EP1'];
	_u = _u		+ ['US_Soldier_Engineer_EP1'];
	_u = _u		+ ['US_Soldier_AMG_EP1'];
	_u = _u		+ ['US_Soldier_AAR_EP1'];
	_u = _u		+ ['US_Soldier_AHAT_EP1'];
	_u = _u		+ ['US_Soldier_AAT_EP1'];
	_u = _u		+ ['US_Soldier_Spotter_EP1'];
	_u = _u		+ ['US_Soldier_TL_EP1'];
	_u = _u		+ ['US_Soldier_SL_EP1'];
	_u = _u		+ ['US_Soldier_Officer_EP1'];
	_u = _u		+ ['US_Soldier_Crew_EP1'];
	_u = _u		+ ['US_Soldier_Pilot_EP1'];
	_u = _u		+ ['US_Delta_Force_EP1'];
	_u = _u		+ ['US_Delta_Force_TL_EP1'];
	_u = _u		+ ['US_Delta_Force_Medic_EP1'];
	_u = _u		+ ['US_Delta_Force_Assault_EP1'];
	_u = _u		+ ['US_Delta_Force_SD_EP1'];
	_u = _u		+ ['US_Delta_Force_MG_EP1'];
	_u = _u		+ ['US_Delta_Force_AR_EP1'];
	_u = _u		+ ['US_Delta_Force_Night_EP1'];
	_u = _u		+ ['US_Delta_Force_Marksman_EP1'];
	_u = _u		+ ['US_Delta_Force_M14_EP1'];
	_u = _u		+ ['US_Delta_Force_Air_Controller_EP1'];
	if (paramDLCBAF) then {
		/* MTP Camo */
		_u = _u		+ ['BAF_Soldier_AA_MTP'];
		_u = _u		+ ['BAF_Soldier_AAA_MTP'];
		_u = _u		+ ['BAF_Soldier_AAT_MTP'];
		_u = _u		+ ['BAF_Soldier_AHAT_MTP'];
		_u = _u		+ ['BAF_Soldier_AAR_MTP'];
		_u = _u		+ ['BAF_Soldier_AMG_MTP'];
		_u = _u		+ ['BAF_Soldier_AT_MTP'];
		_u = _u		+ ['BAF_Soldier_HAT_MTP'];
		_u = _u		+ ['BAF_Soldier_AR_MTP'];
		_u = _u		+ ['BAF_crewman_MTP'];
		_u = _u		+ ['BAF_Soldier_EN_MTP'];
		_u = _u		+ ['BAF_Soldier_GL_MTP'];
		_u = _u		+ ['BAF_Soldier_FAC_MTP'];
		_u = _u		+ ['BAF_Soldier_MG_MTP'];
		_u = _u		+ ['BAF_Soldier_scout_MTP'];
		_u = _u		+ ['BAF_Soldier_Marksman_MTP'];
		_u = _u		+ ['BAF_Soldier_Medic_MTP'];
		_u = _u		+ ['BAF_Soldier_Officer_MTP'];
		_u = _u		+ ['BAF_Pilot_MTP'];
		_u = _u		+ ['BAF_Soldier_MTP'];
		_u = _u		+ ['BAF_ASoldier_MTP'];
		_u = _u		+ ['BAF_Soldier_L_MTP'];
		_u = _u		+ ['BAF_Soldier_N_MTP'];
		_u = _u		+ ['BAF_Soldier_SL_MTP'];
		_u = _u		+ ['BAF_Soldier_SniperN_MTP'];
		_u = _u		+ ['BAF_Soldier_SniperH_MTP'];
		_u = _u		+ ['BAF_Soldier_Sniper_MTP'];
		_u = _u		+ ['BAF_Soldier_spotter_MTP'];
		_u = _u		+ ['BAF_Soldier_spotterN_MTP'];
		_u = _u		+ ['BAF_Soldier_TL_MTP'];
		/* Woodland Camo */
		_u = _u		+ ['BAF_Soldier_AA_W'];
		_u = _u		+ ['BAF_Soldier_AAA_W'];
		_u = _u		+ ['BAF_Soldier_AAT_W'];
		_u = _u		+ ['BAF_Soldier_AHAT_W'];
		_u = _u		+ ['BAF_Soldier_AAR_W'];
		_u = _u		+ ['BAF_Soldier_AMG_W'];
		_u = _u		+ ['BAF_Soldier_AT_W'];
		_u = _u		+ ['BAF_Soldier_HAT_W'];
		_u = _u		+ ['BAF_Soldier_AR_W'];
		_u = _u		+ ['BAF_crewman_W'];
		_u = _u		+ ['BAF_Soldier_EN_W'];
		_u = _u		+ ['BAF_Soldier_GL_W'];
		_u = _u		+ ['BAF_Soldier_FAC_W'];
		_u = _u		+ ['BAF_Soldier_MG_W'];
		_u = _u		+ ['BAF_Soldier_scout_W'];
		_u = _u		+ ['BAF_Soldier_Marksman_W'];
		_u = _u		+ ['BAF_Soldier_Medic_W'];
		_u = _u		+ ['BAF_Soldier_Officer_W'];
		_u = _u		+ ['BAF_Pilot_W'];
		_u = _u		+ ['BAF_Soldier_W'];
		_u = _u		+ ['BAF_ASoldier_W'];
		_u = _u		+ ['BAF_Soldier_L_W'];
		_u = _u		+ ['BAF_Soldier_N_W'];
		_u = _u		+ ['BAF_Soldier_SL_W'];
		_u = _u		+ ['BAF_Soldier_SniperN_W'];
		_u = _u		+ ['BAF_Soldier_SniperH_W'];
		_u = _u		+ ['BAF_Soldier_Sniper_W'];
		_u = _u		+ ['BAF_Soldier_spotter_W'];
		_u = _u		+ ['BAF_Soldier_spotterN_W'];
		_u = _u		+ ['BAF_Soldier_TL_W'];
		/* Desert Camo */
		_u = _u		+ ['BAF_Soldier_AA_DDPM'];
		_u = _u		+ ['BAF_Soldier_AAA_DDPM'];
		_u = _u		+ ['BAF_Soldier_AAT_DDPM'];
		_u = _u		+ ['BAF_Soldier_AHAT_DDPM'];
		_u = _u		+ ['BAF_Soldier_AAR_DDPM'];
		_u = _u		+ ['BAF_Soldier_AMG_DDPM'];
		_u = _u		+ ['BAF_Soldier_AT_DDPM'];
		_u = _u		+ ['BAF_Soldier_HAT_DDPM'];
		_u = _u		+ ['BAF_Soldier_AR_DDPM'];
		_u = _u		+ ['BAF_crewman_DDPM'];
		_u = _u		+ ['BAF_Soldier_EN_DDPM'];
		_u = _u		+ ['BAF_Soldier_GL_DDPM'];
		_u = _u		+ ['BAF_Soldier_FAC_DDPM'];
		_u = _u		+ ['BAF_Soldier_MG_DDPM'];
		_u = _u		+ ['BAF_Soldier_scout_DDPM'];
		_u = _u		+ ['BAF_Soldier_Marksman_DDPM'];
		_u = _u		+ ['BAF_Soldier_Medic_DDPM'];
		_u = _u		+ ['BAF_Soldier_Officer_DDPM'];
		_u = _u		+ ['BAF_Pilot_DDPM'];
		_u = _u		+ ['BAF_Soldier_DDPM'];
		_u = _u		+ ['BAF_ASoldier_DDPM'];
		_u = _u		+ ['BAF_Soldier_L_DDPM'];
		_u = _u		+ ['BAF_Soldier_N_DDPM'];
		_u = _u		+ ['BAF_Soldier_SL_DDPM'];
		_u = _u		+ ['BAF_Soldier_TL_DDPM'];
	};
};

if (WF_A2_CombinedOps) then {
	_u 			= ['US_Soldier_Light_EP1'];
	_u = _u		+ ['US_Soldier_EP1'];
	_u = _u		+ ['US_Soldier_B_EP1'];
	_u = _u		+ ['US_Soldier_LAT_EP1'];
	_u = _u		+ ['US_Soldier_AT_EP1'];
	_u = _u		+ ['US_Soldier_HAT_EP1'];
	_u = _u		+ ['US_Soldier_AA_EP1'];
	_u = _u		+ ['US_Soldier_AR_EP1'];
	_u = _u		+ ['US_Soldier_MG_EP1'];
	_u = _u		+ ['US_Soldier_GL_EP1'];
	_u = _u		+ ['US_Soldier_Sniper_EP1'];
	_u = _u		+ ['US_Soldier_SniperH_EP1'];
	_u = _u		+ ['US_Soldier_Sniper_NV_EP1'];
	_u = _u		+ ['US_Soldier_Marksman_EP1'];
	_u = _u		+ ['US_Soldier_Medic_EP1'];
	_u = _u		+ ['US_Soldier_Engineer_EP1'];
	_u = _u		+ ['US_Soldier_AMG_EP1'];
	_u = _u		+ ['US_Soldier_AAR_EP1'];
	_u = _u		+ ['US_Soldier_AHAT_EP1'];
	_u = _u		+ ['US_Soldier_AAT_EP1'];
	_u = _u		+ ['US_Soldier_Spotter_EP1'];
	_u = _u		+ ['US_Soldier_TL_EP1'];
	_u = _u		+ ['US_Soldier_SL_EP1'];
	_u = _u		+ ['US_Soldier_Officer_EP1'];
	_u = _u		+ ['US_Soldier_Crew_EP1'];
	_u = _u		+ ['US_Soldier_Pilot_EP1'];
	_u = _u		+ ['US_Delta_Force_EP1'];
	_u = _u		+ ['US_Delta_Force_TL_EP1'];
	_u = _u		+ ['US_Delta_Force_Medic_EP1'];
	_u = _u		+ ['US_Delta_Force_Assault_EP1'];
	_u = _u		+ ['US_Delta_Force_SD_EP1'];
	_u = _u		+ ['US_Delta_Force_MG_EP1'];
	_u = _u		+ ['US_Delta_Force_AR_EP1'];
	_u = _u		+ ['US_Delta_Force_Night_EP1'];
	_u = _u		+ ['US_Delta_Force_Marksman_EP1'];
	_u = _u		+ ['US_Delta_Force_M14_EP1'];
	_u = _u		+ ['US_Delta_Force_Air_Controller_EP1'];
	_u = _u		+ ['USMC_Soldier'];
	_u = _u		+ ['USMC_Soldier2'];
	_u = _u		+ ['USMC_Soldier_LAT'];
	_u = _u		+ ['USMC_Soldier_AT'];
	_u = _u		+ ['USMC_Soldier_HAT'];
	_u = _u		+ ['USMC_Soldier_AA'];
	_u = _u		+ ['USMC_Soldier_AR'];
	_u = _u		+ ['USMC_Soldier_MG'];
	_u = _u		+ ['USMC_Soldier_GL'];
	_u = _u		+ ['USMC_SoldierS_Sniper'];
	_u = _u		+ ['USMC_SoldierS_SniperH'];
	_u = _u		+ ['USMC_SoldierM_Marksman'];
	_u = _u		+ ['USMC_Soldier_Medic'];
	_u = _u		+ ['USMC_SoldierS_Engineer'];
	_u = _u		+ ['USMC_SoldierS'];
	_u = _u		+ ['USMC_SoldierS_Spotter'];
	_u = _u		+ ['USMC_Soldier_TL'];
	_u = _u		+ ['USMC_Soldier_SL'];
	_u = _u		+ ['USMC_Soldier_Crew'];
	_u = _u		+ ['USMC_Soldier_Pilot'];
	_u = _u		+ ['FR_GL'];
	_u = _u		+ ['FR_Corpsman'];
	_u = _u		+ ['FR_Assault_R'];
	_u = _u		+ ['FR_Assault_GL'];
	_u = _u		+ ['FR_AR'];
	_u = _u		+ ['FR_R'];
	_u = _u		+ ['FR_Sapper'];
	_u = _u		+ ['FR_AC'];
	_u = _u		+ ['FR_Marksman'];
	if (paramDLCBAF) then {
		/* MTP Camo */
		_u = _u		+ ['BAF_Soldier_AA_MTP'];
		_u = _u		+ ['BAF_Soldier_AAA_MTP'];
		_u = _u		+ ['BAF_Soldier_AAT_MTP'];
		_u = _u		+ ['BAF_Soldier_AHAT_MTP'];
		_u = _u		+ ['BAF_Soldier_AAR_MTP'];
		_u = _u		+ ['BAF_Soldier_AMG_MTP'];
		_u = _u		+ ['BAF_Soldier_AT_MTP'];
		_u = _u		+ ['BAF_Soldier_HAT_MTP'];
		_u = _u		+ ['BAF_Soldier_AR_MTP'];
		_u = _u		+ ['BAF_crewman_MTP'];
		_u = _u		+ ['BAF_Soldier_EN_MTP'];
		_u = _u		+ ['BAF_Soldier_GL_MTP'];
		_u = _u		+ ['BAF_Soldier_FAC_MTP'];
		_u = _u		+ ['BAF_Soldier_MG_MTP'];
		_u = _u		+ ['BAF_Soldier_scout_MTP'];
		_u = _u		+ ['BAF_Soldier_Marksman_MTP'];
		_u = _u		+ ['BAF_Soldier_Medic_MTP'];
		_u = _u		+ ['BAF_Soldier_Officer_MTP'];
		_u = _u		+ ['BAF_Pilot_MTP'];
		_u = _u		+ ['BAF_Soldier_MTP'];
		_u = _u		+ ['BAF_ASoldier_MTP'];
		_u = _u		+ ['BAF_Soldier_L_MTP'];
		_u = _u		+ ['BAF_Soldier_N_MTP'];
		_u = _u		+ ['BAF_Soldier_SL_MTP'];
		_u = _u		+ ['BAF_Soldier_SniperN_MTP'];
		_u = _u		+ ['BAF_Soldier_SniperH_MTP'];
		_u = _u		+ ['BAF_Soldier_Sniper_MTP'];
		_u = _u		+ ['BAF_Soldier_spotter_MTP'];
		_u = _u		+ ['BAF_Soldier_spotterN_MTP'];
		_u = _u		+ ['BAF_Soldier_TL_MTP'];
		/* Woodland Camo */
		_u = _u		+ ['BAF_Soldier_AA_W'];
		_u = _u		+ ['BAF_Soldier_AAA_W'];
		_u = _u		+ ['BAF_Soldier_AAT_W'];
		_u = _u		+ ['BAF_Soldier_AHAT_W'];
		_u = _u		+ ['BAF_Soldier_AAR_W'];
		_u = _u		+ ['BAF_Soldier_AMG_W'];
		_u = _u		+ ['BAF_Soldier_AT_W'];
		_u = _u		+ ['BAF_Soldier_HAT_W'];
		_u = _u		+ ['BAF_Soldier_AR_W'];
		_u = _u		+ ['BAF_crewman_W'];
		_u = _u		+ ['BAF_Soldier_EN_W'];
		_u = _u		+ ['BAF_Soldier_GL_W'];
		_u = _u		+ ['BAF_Soldier_FAC_W'];
		_u = _u		+ ['BAF_Soldier_MG_W'];
		_u = _u		+ ['BAF_Soldier_scout_W'];
		_u = _u		+ ['BAF_Soldier_Marksman_W'];
		_u = _u		+ ['BAF_Soldier_Medic_W'];
		_u = _u		+ ['BAF_Soldier_Officer_W'];
		_u = _u		+ ['BAF_Pilot_W'];
		_u = _u		+ ['BAF_Soldier_W'];
		_u = _u		+ ['BAF_ASoldier_W'];
		_u = _u		+ ['BAF_Soldier_L_W'];
		_u = _u		+ ['BAF_Soldier_N_W'];
		_u = _u		+ ['BAF_Soldier_SL_W'];
		_u = _u		+ ['BAF_Soldier_SniperN_W'];
		_u = _u		+ ['BAF_Soldier_SniperH_W'];
		_u = _u		+ ['BAF_Soldier_Sniper_W'];
		_u = _u		+ ['BAF_Soldier_spotter_W'];
		_u = _u		+ ['BAF_Soldier_spotterN_W'];
		_u = _u		+ ['BAF_Soldier_TL_W'];
		/* Desert Camo */
		_u = _u		+ ['BAF_Soldier_AA_DDPM'];
		_u = _u		+ ['BAF_Soldier_AAA_DDPM'];
		_u = _u		+ ['BAF_Soldier_AAT_DDPM'];
		_u = _u		+ ['BAF_Soldier_AHAT_DDPM'];
		_u = _u		+ ['BAF_Soldier_AAR_DDPM'];
		_u = _u		+ ['BAF_Soldier_AMG_DDPM'];
		_u = _u		+ ['BAF_Soldier_AT_DDPM'];
		_u = _u		+ ['BAF_Soldier_HAT_DDPM'];
		_u = _u		+ ['BAF_Soldier_AR_DDPM'];
		_u = _u		+ ['BAF_crewman_DDPM'];
		_u = _u		+ ['BAF_Soldier_EN_DDPM'];
		_u = _u		+ ['BAF_Soldier_GL_DDPM'];
		_u = _u		+ ['BAF_Soldier_FAC_DDPM'];
		_u = _u		+ ['BAF_Soldier_MG_DDPM'];
		_u = _u		+ ['BAF_Soldier_scout_DDPM'];
		_u = _u		+ ['BAF_Soldier_Marksman_DDPM'];
		_u = _u		+ ['BAF_Soldier_Medic_DDPM'];
		_u = _u		+ ['BAF_Soldier_Officer_DDPM'];
		_u = _u		+ ['BAF_Pilot_DDPM'];
		_u = _u		+ ['BAF_Soldier_DDPM'];
		_u = _u		+ ['BAF_ASoldier_DDPM'];
		_u = _u		+ ['BAF_Soldier_L_DDPM'];
		_u = _u		+ ['BAF_Soldier_N_DDPM'];
		_u = _u		+ ['BAF_Soldier_SL_DDPM'];
		_u = _u		+ ['BAF_Soldier_TL_DDPM'];
	};
};

['WFBE_WESTBARRACKSUNITS',_u,true] Call SetNamespace;
if (local player) then {['BARRACKS','WEST',_u] Call Compile preProcessFile 'Client\Init\Init_Faction.sqf'};

if (paramAllies) then {
	//--- CDF Allies.
	_u			= ['CDF_Soldier'];
	_u = _u		+ ['CDF_Soldier_Engineer'];
	_u = _u		+ ['CDF_Soldier_Light'];
	_u = _u		+ ['CDF_Soldier_GL'];
	_u = _u		+ ['CDF_Soldier_Militia'];
	_u = _u		+ ['CDF_Soldier_Medic'];
	_u = _u		+ ['CDF_Soldier_Sniper'];
	_u = _u		+ ['CDF_Soldier_Spotter'];
	_u = _u		+ ['CDF_Soldier_Marksman'];
	_u = _u		+ ['CDF_Soldier_RPG'];
	_u = _u		+ ['CDF_Soldier_Strela'];
	_u = _u		+ ['CDF_Soldier_AR'];
	_u = _u		+ ['CDF_Soldier_MG'];
	_u = _u		+ ['CDF_Soldier_TL'];
	_u = _u		+ ['CDF_Soldier_Officer'];
	_u = _u		+ ['CDF_Commander'];
	_u = _u		+ ['CDF_Soldier_Pilot'];
	_u = _u		+ ['CDF_Soldier_Crew'];
	
	['WFBE_WESTALLIESBARRACKSUNITS',_u,true] Call SetNamespace;	
	['WFBE_WESTALLIESSOLDIER','CDF_Soldier',true] Call SetNamespace;
	
	//--- Insurgent Allies.
	_u			= ['Ins_Soldier_1'];
	_u = _u		+ ['Ins_Soldier_2'];
	_u = _u		+ ['Ins_Soldier_GL'];
	_u = _u		+ ['Ins_Soldier_CO'];
	_u = _u		+ ['Ins_Commander'];
	_u = _u		+ ['Ins_Soldier_Medic'];
	_u = _u		+ ['Ins_Soldier_AR'];
	_u = _u		+ ['Ins_Soldier_MG'];
	_u = _u		+ ['Ins_Soldier_AT'];
	_u = _u		+ ['Ins_Soldier_AA'];
	_u = _u		+ ['Ins_Soldier_Sniper'];
	_u = _u		+ ['Ins_Soldier_Sapper'];
	_u = _u		+ ['Ins_Soldier_Sab'];
	_u = _u		+ ['Ins_Soldier_Pilot'];
	_u = _u		+ ['Ins_Soldier_Crew'];

	['WFBE_EASTALLIESBARRACKSUNITS',_u,true] Call SetNamespace;	
	['WFBE_EASTALLIESSOLDIER','Ins_Soldier_1',true] Call SetNamespace;
} else {
	['WFBE_WESTALLIESBARRACKSUNITS',[],true] Call SetNamespace;
	['WFBE_EASTALLIESBARRACKSUNITS',[],true] Call SetNamespace;
};

/* EAST - Barracks */
if (WF_A2_Vanilla) then {
	_u 			= ['RU_Soldier'];
	_u = _u		+ ['RU_Soldier2'];
	_u = _u		+ ['RU_Soldier_LAT'];
	_u = _u		+ ['RU_Soldier_AT'];
	_u = _u		+ ['RU_Soldier_HAT'];
	_u = _u		+ ['RU_Soldier_AA'];
	_u = _u		+ ['RU_Soldier_AR'];
	_u = _u		+ ['RU_Soldier_MG'];
	_u = _u		+ ['RU_Soldier_GL'];
	_u = _u		+ ['RU_Soldier_Marksman'];
	_u = _u		+ ['RU_Soldier_Sniper'];
	_u = _u		+ ['RU_Soldier_SniperH'];
	_u = _u		+ ['RU_Soldier_Medic'];
	_u = _u		+ ['RU_Soldier_TL'];
	_u = _u		+ ['RU_Soldier_SL'];
	_u = _u		+ ['RU_Soldier_Crew'];
	_u = _u		+ ['RU_Soldier_Pilot'];
	_u = _u		+ ['RUS_Soldier1'];
	_u = _u		+ ['RUS_Soldier2'];
	_u = _u		+ ['RUS_Soldier_GL'];
	_u = _u		+ ['RUS_Commander'];
	_u = _u		+ ['RUS_Soldier_Marksman'];
	_u = _u		+ ['RUS_Soldier3'];
	_u = _u		+ ['RUS_Soldier_TL'];
	_u = _u		+ ['MVD_Soldier_GL'];
	_u = _u		+ ['MVD_Soldier_MG'];
	_u = _u		+ ['MVD_Soldier_Marksman'];
	_u = _u		+ ['MVD_Soldier_AT'];
	_u = _u		+ ['MVD_Soldier_Sniper'];
	_u = _u		+ ['MVD_Soldier_TL'];
};

if (WF_A2_Arrowhead) then {
	_u 			= ['TK_Soldier_EP1'];
	_u = _u		+ ['TK_Soldier_B_EP1'];
	_u = _u		+ ['TK_Soldier_TWS_EP1'];
	_u = _u		+ ['TK_Soldier_Engineer_EP1'];
	_u = _u		+ ['TK_Soldier_LAT_EP1'];
	_u = _u		+ ['TK_Soldier_AT_EP1'];
	_u = _u		+ ['TK_Soldier_HAT_EP1'];
	_u = _u		+ ['TK_Soldier_AA_EP1'];
	_u = _u		+ ['TK_Soldier_AR_EP1'];
	_u = _u		+ ['TK_Soldier_MG_EP1'];
	_u = _u		+ ['TK_Soldier_GL_EP1'];
	_u = _u		+ ['TK_Soldier_Spotter_EP1'];
	_u = _u		+ ['TK_Soldier_Medic_EP1'];
	_u = _u		+ ['TK_Special_Forces_EP1'];
	_u = _u		+ ['TK_Special_Forces_TL_EP1'];
	_u = _u		+ ['TK_Special_Forces_MG_EP1'];
	_u = _u		+ ['TK_Soldier_Crew_EP1'];
	_u = _u		+ ['TK_Soldier_Pilot_EP1'];
	_u = _u		+ ['TK_Soldier_SL_EP1'];
	_u = _u		+ ['TK_Soldier_Officer_EP1'];
};

if (WF_A2_CombinedOps) then {
	_u 			= ['RU_Soldier'];
	_u = _u		+ ['RU_Soldier2'];
	_u = _u		+ ['RU_Soldier_LAT'];
	_u = _u		+ ['RU_Soldier_AT'];
	_u = _u		+ ['RU_Soldier_HAT'];
	_u = _u		+ ['RU_Soldier_AA'];
	_u = _u		+ ['RU_Soldier_AR'];
	_u = _u		+ ['RU_Soldier_MG'];
	_u = _u		+ ['RU_Soldier_GL'];
	_u = _u		+ ['RU_Soldier_Marksman'];
	_u = _u		+ ['RU_Soldier_Sniper'];
	_u = _u		+ ['RU_Soldier_SniperH'];
	_u = _u		+ ['RU_Soldier_Medic'];
	_u = _u		+ ['RU_Soldier_TL'];
	_u = _u		+ ['RU_Soldier_SL'];
	_u = _u		+ ['RU_Soldier_Crew'];
	_u = _u		+ ['RU_Soldier_Pilot'];
	_u = _u		+ ['RUS_Soldier1'];
	_u = _u		+ ['RUS_Soldier2'];
	_u = _u		+ ['RUS_Soldier_GL'];
	_u = _u		+ ['RUS_Commander'];
	_u = _u		+ ['RUS_Soldier_Marksman'];
	_u = _u		+ ['RUS_Soldier3'];
	_u = _u		+ ['RUS_Soldier_TL'];
	_u = _u		+ ['MVD_Soldier_GL'];
	_u = _u		+ ['MVD_Soldier_MG'];
	_u = _u		+ ['MVD_Soldier_Marksman'];
	_u = _u		+ ['MVD_Soldier_AT'];
	_u = _u		+ ['MVD_Soldier_Sniper'];
	_u = _u		+ ['MVD_Soldier_TL'];
	_u = _u		+ ['TK_Soldier_EP1'];
	_u = _u		+ ['TK_Soldier_B_EP1'];
	_u = _u		+ ['TK_Soldier_TWS_EP1'];
	_u = _u		+ ['TK_Soldier_Engineer_EP1'];
	_u = _u		+ ['TK_Soldier_LAT_EP1'];
	_u = _u		+ ['TK_Soldier_AT_EP1'];
	_u = _u		+ ['TK_Soldier_HAT_EP1'];
	_u = _u		+ ['TK_Soldier_AA_EP1'];
	_u = _u		+ ['TK_Soldier_AR_EP1'];
	_u = _u		+ ['TK_Soldier_MG_EP1'];
	_u = _u		+ ['TK_Soldier_GL_EP1'];
	_u = _u		+ ['TK_Soldier_Spotter_EP1'];
	_u = _u		+ ['TK_Soldier_Medic_EP1'];
	_u = _u		+ ['TK_Special_Forces_EP1'];
	_u = _u		+ ['TK_Special_Forces_TL_EP1'];
	_u = _u		+ ['TK_Special_Forces_MG_EP1'];
	_u = _u		+ ['TK_Soldier_Crew_EP1'];
	_u = _u		+ ['TK_Soldier_Pilot_EP1'];
	_u = _u		+ ['TK_Soldier_SL_EP1'];
	_u = _u		+ ['TK_Soldier_Officer_EP1'];
};

['WFBE_EASTBARRACKSUNITS',_u,true] Call SetNamespace;
if (local player) then {['BARRACKS','EAST',_u] Call Compile preProcessFile 'Client\Init\Init_Faction.sqf'};

_u = [];

/* RESISTANCE - Barracks */
if (WF_A2_Vanilla || WF_A2_CombinedOps) then {
	_u 			= ['GUE_Soldier_1'];
	_u = _u		+ ['GUE_Soldier_2'];
	_u = _u		+ ['GUE_Soldier_3'];
	_u = _u		+ ['GUE_Soldier_GL'];
	_u = _u		+ ['GUE_Soldier_AT'];
	_u = _u		+ ['GUE_Soldier_AA'];
	_u = _u		+ ['GUE_Soldier_AR'];
	_u = _u		+ ['GUE_Soldier_MG'];
	_u = _u		+ ['GUE_Soldier_Sniper'];
	_u = _u		+ ['GUE_Soldier_Medic'];
	_u = _u		+ ['GUE_Soldier_Crew'];
	_u = _u		+ ['GUE_Soldier_Pilot'];
	_u = _u		+ ['GUE_Soldier_Scout'];
	_u = _u		+ ['GUE_Soldier_Sab'];
	_u = _u		+ ['GUE_Commander'];
	_u = _u		+ ['GUE_Worker2'];
	_u = _u		+ ['GUE_Woodlander3'];
	_u = _u		+ ['GUE_Villager3'];
	_u = _u		+ ['GUE_Woodlander2'];
	_u = _u		+ ['GUE_Woodlander1'];
	_u = _u		+ ['GUE_Villager4'];
};

if (WF_A2_Arrowhead || WF_A2_CombinedOps) then {
	_u 			= ['TK_GUE_Soldier_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_2_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_3_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_4_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_5_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_AT_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_AAT_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_AA_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_AR_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_MG_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_Sniper_EP1'];
	_u = _u		+ ['TK_GUE_Bonesetter_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_HAT_EP1'];
	_u = _u		+ ['TK_GUE_Soldier_TL_EP1'];
	_u = _u		+ ['TK_GUE_Warlord_EP1'];
};

['WFBE_GUERBARRACKSUNITS',_u,true] Call SetNamespace;

if (WF_A2_Vanilla) then {
	['WFBE_WESTSOLDIER','USMC_Soldier',true] Call SetNamespace;
	['WFBE_EASTSOLDIER','RU_Soldier',true] Call SetNamespace;
	['WFBE_GUERSOLDIER','GUE_Soldier_1',true] Call SetNamespace;
};

if (WF_A2_Arrowhead) then {
	['WFBE_WESTSOLDIER','US_Soldier_EP1',true] Call SetNamespace;
	['WFBE_EASTSOLDIER','TK_Soldier_EP1',true] Call SetNamespace;
	['WFBE_GUERSOLDIER','TK_GUE_Soldier_EP1',true] Call SetNamespace;
};

if (WF_A2_CombinedOps) then {
	_resType = 'WFBE_RESISTANCEFACTION' Call GetNamespace;
	if (isNil '_resType') then {_resType = -1};
	['WFBE_WESTSOLDIER','US_Soldier_EP1',true] Call SetNamespace;
	['WFBE_EASTSOLDIER','RU_Soldier',true] Call SetNamespace;
	switch (_resType) do {
		case 0: {['WFBE_GUERSOLDIER','GUE_Soldier_1',true] Call SetNamespace};
		case 1: {['WFBE_GUERSOLDIER','TK_GUE_Soldier_EP1',true] Call SetNamespace};
	};
};

westSoldierBaseClass = 'SoldierWB';
eastSoldierBaseClass = 'SoldierEB';
resistanceSoldierBaseClass = 'SoldierGB';

_longestBarracksBuildTime = 0;
{
	_c = _x Call GetNamespace;
	if !(isNil '_c') then {
		if ((_c select QUERYUNITTIME) > _longestBarracksBuildTime) then {
			_longestBarracksBuildTime = (_c select QUERYUNITTIME);
		};
	} else {
		diag_log Format ["[WFBE (ERROR)] Config_Barracks: '%1' is not defined in the Core files.",_x];
	};
} forEach (('WFBE_EASTBARRACKSUNITS' Call GetNamespace) + ('WFBE_WESTBARRACKSUNITS' Call GetNamespace) + ('WFBE_GUERBARRACKSUNITS' Call GetNamespace));

['WFBE_LONGESTBARRACKSBUILDTIME',_longestBarracksBuildTime,true] Call SetNamespace;
diag_log "[WFBE (INIT)] Config_Barracks: Initialization - [Done]";