using System;
using System.Collections.Generic;
using System.Linq;

namespace ArmA2.Script.ScriptProcessor
{
    public partial class Processor
    {
        private static List<string> _commands;
        public static List<string> Commands
        {
            get
            {
                if (_commands == null)
                {
                    _commands = ReadUniqueItemCollection(_commandList, "Duplicated command");
                }
                return _commands;
            }
        }

        private static List<string> ReadUniqueItemCollection(string content, string warningMessage)
        {
            var groups = content.Split("\n".ToCharArray(), StringSplitOptions.RemoveEmptyEntries)
                .Select(m => m.Trim())
                .Where(m => m.Length > 0)
                .GroupBy(m => m);

            groups.Where(m => m.Count() > 0).ForEach(n =>
            {
                if (n.Count() > 1)
                    Logger.Log(LoggingLevel.Warning, "{0}: '{1}'", warningMessage, n.Key);
            });

            return groups.Select(m => m.Key)
                .OrderByDescending(m => m.Length)
                .ToList();
        }


        private const string _commandList = @"
abs
accTime
acos
action
actionKeys
actionKeysImages
actionKeysNames
actionKeysNamesArray
activateAddons
activateKey
addAction
addBackpack
addBackpackCargo
addCamShake
addEditorObject
addEventHandler
addGroupIcon
addLiveStats
addMagazine
addMagazineCargo
addMagazineCargoGlobal
addMagazinePool
addMagazineTurret
addMenu
addMenuItem
addMPEventHandler
addPublicVariableEventHandler
addRating
addResources
addScore
addSwitchableUnit
addTeamMember
addVehicle
addWaypoint
addWeapon
addWeaponCargo
addWeaponCargoGlobal
addWeaponPool
agent
agents
aimedAtTarget
airportSide
AISFinishHeal
alive
allDead
allGroups
allMissionObjects
allow3DMode
allowDamage
allowDammage
allowFileOperations
allowFleeing
allowGetIn
allUnits
ammo
and
animate
animationPhase
animationState
armoryPoints
asin
assert
assignAsCargo
assignAsCommander
assignAsDriver
assignAsGunner
assignedCargo
assignedCommander
assignedDriver
assignedGunner
assignedTarget
assignedVehicle
assignedVehicleRole
assignTeam
assignToAirport
atan
atan2
atg
attachedObject
attachObject
attachTo
attackEnabled

backpackSpaceFor
behaviour
benchmark
boundingBox
boundingCenter
breakOut
breakTo
buildingExit
buildingPos
buttonAction
buttonSetAction

cadetMode
call
camCommand
camCommit
camCommitPrepared
camCommitted
camConstuctionSetParams
camCreate
camDestroy
cameraEffect
cameraEffectEnableHUD
cameraInterest
cameraOn
cameraView
campaignConfigFile
camPreload
camPreloaded
camPrepareBank
camPrepareDir
camPrepareDive
camPrepareFocus
camPrepareFov
camPrepareFovRange
camPreparePos
camPrepareRelPos
camPrepareTarget
camSetBank
camSetDir
camSetDive
camSetFocus
camSetFov
camSetFovRange
camSetPos
camSetRelPos
camSetTarget
camTarget
camUseNVG
canFire
canMove
canStand
canUnloadInCombat
captive
captiveNum
case
catch
ceil
cheatsEnabled
checkAIFeature
civilian
clearBackpackCargoGlobal
clearGroupIcons
clearMagazineCargo
clearMagazineCargoGlobal
clearMagazinePool
clearOverlay
clearRadio
clearVehicleInit
clearWeaponCargo
clearWeaponCargoGlobal
clearWeaponPool
closeDialog
closeDisplay
closeOverlay
collapseObjectTree
combatMode
commandChat
commander
commandFire
commandFollow
commandFSM
commandGetOut
commandingMenu
commandMove
commandRadio
commandStop
commandTarget
commandWatch
comment
commitOverlay
compile
completedFSM
composeText
configFile
configName
controlNull
copyFromClipboard
copyToClipboard
copyWaypoints
cos
count
countEnemy
countFriendly
countSide
countType
countUnknown
createAgent
createCenter
createDialog
createDiaryLink
createDiaryRecord
createDiarySubject
createDisplay
createGearDialog
createGroup
createGuardedPoint
createLocation
createMarker
createMarkerLocal
createMenu
createMine
createMissionDisplay
createSimpleTask
createSoundSource
createTarget
createTask
createTeam
createTrigger
createUnit
createUnit array
createVehicle
createVehicle array
createVehicleLocal
crew
ctrlActivate
ctrlAddEventHandler
ctrlAutoScrollDelay
ctrlAutoScrollRewind
ctrlAutoScrollSpeed
ctrlCommit
ctrlCommitted
ctrlEnable
ctrlEnabled
ctrlFade
ctrlMapAnimAdd
ctrlMapAnimClear
ctrlMapAnimCommit
ctrlMapAnimDone
ctrlMapCursor
ctrlMapMouseOver
ctrlMapScale
ctrlMapScreenToWorld
ctrlMapWorldToScreen
ctrlParent
ctrlPosition
ctrlRemoveAllEventHandlers
ctrlRemoveEventHandler
ctrlScale
ctrlSetActiveColor
ctrlSetAutoScrollDelay
ctrlSetAutoScrollRewind
ctrlSetAutoScrollSpeed
ctrlSetBackgroundColor
ctrlSetEventHandler
ctrlSetFade
ctrlSetFocus
ctrlSetFont
ctrlSetFontH1
ctrlSetFontH1B
ctrlSetFontH2
ctrlSetFontH2B
ctrlSetFontH3
ctrlSetFontH3B
ctrlSetFontH4
ctrlSetFontH4B
ctrlSetFontH5
ctrlSetFontH5B
ctrlSetFontH6
ctrlSetFontH6B
ctrlSetFontHeight
ctrlSetFontHeightH1
ctrlSetFontHeightH2
ctrlSetFontHeightH3
ctrlSetFontHeightH4
ctrlSetFontHeightH5
ctrlSetFontHeightH6
ctrlSetFontP height
ctrlSetFontP name
ctrlSetFontPB
ctrlSetForegroundColor
ctrlSetPosition
ctrlSetScale
ctrlSetStructuredText
ctrlSetText
ctrlSetTextColor
ctrlSetTooltip
ctrlSetTooltipColorBox
ctrlSetTooltipColorShade
ctrlSetTooltipColorText
ctrlShow
ctrlShown
ctrlText
ctrlType
ctrlVisible
currentCommand
currentMagazine
currentMuzzle
currentTask
currentTasks
currentVisionMode
currentWaypoint
currentWeapon
currentWeaponMode
currentZeroing
cursorTarget
cutFadeOut
cutObj
cutRsc
cutText

damage
date
dateToNumber
daytime
debugLog
default
deg
deleteCenter
deleteCollection
deleteEditorObject
deleteGroup
deleteIdentity
deleteLocation
deleteMarker
deleteMarkerLocal
deleteResources
deleteStatus
deleteTarget
deleteTeam
deleteVehicle
deleteWaypoint
detach
diag fps
diag fpsmin
diag frameno
diag log
diag tickTime
dialog
diarySubjectExists
difficultyEnabled
direction
directSay
disableAI
disableConversation
disableSerialization
disableTIEquipment
disableUserInput
displayAddEventHandler
displayCtrl
displayNull
displayRemoveAllEventHandlers
displayRemoveEventHandler
displaySetEventHandler
dissolveTeam
distance
distributionRegion
do
doFire
doFollow
doFSM
doGetOut
doMove
doStop
doTarget
doWatch
drawArrow
drawEllipse
drawIcon
drawLine
drawLink
drawLocation
drawRectangle
driver
drop

east
echo
editObject
editorSetEventHandler
effectiveCommander
else
emptyPositions
enableAI
enableAIFeature
enableAttack
enableCamShake
enableEndDialog
enableEngineArtillery
enableEnvironment
enableGunLights
enableIRLasers
enableRadio
enableReload
enableSaving
enableSentences
enableSimulation
enableTeamSwitch
endLoadingScreen
endMission
enemy
engineOn
estimatedEndServerTime
estimatedTimeLeft

evalObjectArgument
exec
execEditorScript
execFSM
execVM
exit
exitWith
exp
expectedDestination
exportLandscapeXYZ

faction
fadeMusic
fadeRadio
fadeSound
fadeSpeech
failMission
false
fillWeaponsFromPool
find
findCover
findDisplay
findEditorObject
findEmptyPosition
findEmptyPositionReady
findNearestEnemy
finishMissionInit
finite
fire
fireAtTarget
flag
flagOwner
fleeing
floor
flyInHeight
fog
fogForecast
for
forceEnd
forceMap
forceSpeed
forceWalk
forEach
forEachMember
forEachMemberAgent
forEachMemberTeam
format
formation
formationDirection
formationLeader
formationMembers
formationPosition
formationTask
formatText
formLeader
friendly
from
fromEditor
fuel

gearSlotData
getArray
getBackpackCargo
getDammage
getDir
getEditorCamera
getEditorMode
getEditorObjectScope
getElevationOffset
getFriend
getFSMVariable
getGroupIcon
getGroupIconParams
getGroupIcons
getHideFrom
getMagazineCargo
getMarkerColor
getMarkerPos
getMarkerSize
getMarkerType
getNumber
getObjectArgument
getObjectChildren
getObjectProxy
getPlayerUID
getPos
getPosASL
getPosATL
getResolution
getSpeed
getTerrainHeightASL
getText
getVariable
getWeaponCargo
getWPPos
glanceAt
globalChat
globalRadio
goto
group
groupChat
groupIconSelectable
groupIconsVisible
groupRadio
groupSelectedUnits
groupSelectUnit
grpNull
gunner

halt
handsHit
hasWeapon
hcAllGroups
hcGroupParams
hcLeader
hcRemoveAllGroups
hcRemoveGroup
hcSelected
hcSelectGroup
hcSetGroup
hcShowBar
hcShownBar
hideBehindScripted
hideBody
hideObject
hierarchyObjectsCount
hint
hintC
hintCadet
hintSilent
hostMission
htmlLoad

if
image
importAllGroups
importance
in
inflame
inflamed
inGameUISetEventHandler
inheritsFrom
initAmbientLife
inputAction
insertEditorObject
intersect
isAgent
isArray
isAutoHoverOn
isClass
isDedicated
isEngineOn
isFlatEmpty
isForcedWalk
isFormationLeader
isHidden
isHideBehindScripted
isKeyActive
isKindOf
isManualFire
isMarkedForCollection
isMultiplayer
isNil
isNull
isNumber
isOnRoad
isPlayer
isRealTime
isServer
isShowing3DIcons
isText
isWalking
items

join
joinAs
joinAsSilent
joinSilent

kbAddDatabase
kbAddDatabaseTargets
kbAddTopic
kbHasTopic
kbReact
kbRemoveTopic
kbTell
kbWasSaid
keyImage
keyName
knowsAbout

land
landAt
landResult
laserTarget
lbAdd
lbClear
lbColor
lbCurSel
lbData
lbDelete
lbIsSelected
lbPicture
lbSelection
lbSetColor
lbSetCurSel
lbSetData
lbSetPicture
lbSetSelected
lbSetValue
lbSize
lbSort
lbSortByValue
lbText
lbValue
leader
leaveVehicle
lifeState
lightAttachObject
lightDetachObject
lightIsOn
limitSpeed
lineBreak
list
listObjects
ln
lnbAddArray
lnbAddColumn
lnbAddRow
lnbClear
lnbColor
lnbCurSelRow
lnbData
lnbDeleteColumn
lnbDeleteRow
lnbGetColumnsPosition
lnbPicture
lnbSetColor
lnbsetColumnsPos
lnbSetCurSelRow
lnbSetData
lnbSetPicture
lnbSetText
lnbSetValue
lnbSize
lnbText
lnbValue
loadFile
loadGame
loadIdentity
loadOverlay
loadStatus
local
localize
locationNull
locationPosition
lock
lockCargo
lockDriver
locked
lockedCargo
lockedDriver
lockedTurret
lockTurret
lockWP
lockWp
log
lookAt
lookAtPos

magazines
magazinesTurret
mapAnimAdd
mapAnimClear
mapAnimCommit
mapAnimDone
mapCenterOnCamera
mapGridPosition
markerAlpha
markerBrush
markerColor
markerDir
markerPos
markerShape
markerSize
markerText
markerType
max
members
min
missionConfigFile
missionName
missionNamespace
missionStart
mod
modelToWorld
morale
move
moveInCargo
moveInCommander
moveInDriver
moveInGunner
moveInTurret
moveObjectToEnd
moveOut
moveTarget
moveTime
moveTo
moveToCompleted
moveToFailed
musicVolume

name
name location
nearEntities
nearestBuilding
nearestLocation
nearestLocations
nearestLocationWithDubbing
nearestObject
nearestObjects
nearObjects
nearObjectsReady
nearRoads
nearTargets
needReload
newOverlay
nextMenuItemIndex
nextWeatherChange
nil
nMenuItems
not
NumberToDate

object
objNull
objStatus
onBriefingGear
onBriefingGroup
onBriefingNotes
onBriefingPlan
onBriefingTeamSwitch
onCommandModeChanged
onDoubleClick
onGroupIconClick
onGroupIconOverEnter
onGroupIconOverLeave
onHCGroupSelectionChanged
onMapSingleClick
onPlayerConnected
onPlayerDisconnected
onPreloadFinished
onPreloadStarted
onShowNewObject
onTeamSwitch
openDSInterface
openMap
or
orderGetIn
overcast
overcastForecast
owner

parseNumber
parseText
parsingNamespace
pi
pickWeaponPool
playableUnits
playAction
playActionNow
player
playerRespawnTime
playerSide
playersNumber
playGesture
playMission
playMove
playMoveNow
playMusic
playScriptedMission
playSound
position
position location
posScreenToWorld
positionCameraToWorld
posWorldToScreen
ppEffectAdjust
ppEffectCommit
ppEffectCommitted
ppEffectCreate
ppEffectDestroy
ppEffectEnable
precision
preloadCamera
preloadObject
preloadSound
preloadTitleObj
preloadTitleRsc
preprocessFile
preprocessFileLineNumbers
primaryWeapon
priority
private
processDiaryLink
processInitCommands
progressLoadingScreen
progressPosition
progressSetPosition
publicVariable
putWeaponPool

queryMagazinePool
queryWeaponPool

rad
radioVolume
rain
random
rank
rankId
rating
rectangular
R cont.
registeredTasks
registerTask
reload
reloadEnabled
remoteControl
removeAction
removeAllEventHandlers
removeAllItems
removeAllMPEventHandlers
removeAllWeapons
removeBackpack
removeDrawIcon
removeDrawLinks
removeEventHandler
removeGroupIcon
removeMagazine
removeMagazines
removeMagazinesTurret
removeMagazineTurret
removeMenuItem
removeMPEventHandler
removeSimpleTask
removeSwitchableUnit
removeTeamMember
removeWeapon
requiredVersion
resetCamShake
resistance
resize
resources
respawnVehicle
restartEditorCamera
reveal
reversedMouseY
roadsConnectedTo
round
runInitScript

safeZoneH
safeZoneW
safeZoneWAbs
safeZoneX
safeZoneXAbs
safeZoneY
saveGame
saveIdentity
saveOverlay
saveStatus
saveVar
savingEnabled
say
say2D
say3D
scopeName
score
scoreSide
screenToWorld
scriptDone
scriptName
scudState
secondaryWeapon
select
selectBestPlaces
selectDiarySubject
selectedEditorObjects
selectEditorObject
selectionPosition
selectLeader
selectNoPlayer
selectPlayer
selectWeapon
sendSimpleCommand
sendTask
sendTaskResult
sendUDPMessage
serverCommand
serverCommandAvailable
serverTime
set
setAccTime
setAirportSide
setAmmoCargo
setAperture
setArmoryPoints
setAttributes
setBehaviour
setCameraEffect
setCameraInterest
setCamShakeDefParams
setCamShakeParams
setCamUseTi
setCaptive
setCombatMode
setCurrentTask
setCurrentWaypoint
setDamage
setDammage
setDate
setDestination
setDir
setDirection
setDrawIcon
setDropInterval
setEditorMode
setEditorObjectScope
setEffectCondition
setFace
setFaceAnimation
setFlagOwner
setFlagSide
setFlagTexture
setFog
setFormation
setFormationTask
setFormDir
setFriend
setFromEditor
setFSMVariable
setFuel
setFuelCargo
setGroupIcon
setGroupIconParams
setGroupIconsSelectable
setGroupIconsVisible
setGroupId
setHit
setHideBehind
setIdentity
setImportance
setLeader
setLightAmbient
setLightBrightness
setLightColor
setMarkerAlpha
setMarkerAlphaLocal
setMarkerBrush
setMarkerBrushLocal
setMarkerColor
setMarkerColorLocal
setMarkerDir
setMarkerDirLocal
setMarkerPos
setMarkerPosLocal
setMarkerShape
setMarkerShapeLocal
setMarkerSize
setMarkerSizeLocal
setMarkerText
setMarkerTextLocal
setMarkerType
setMarkerTypeLocal
setMimic
setMousePosition
setMusicEffect
setName
setObjectArguments
setObjectProxy
setObjectTexture
setOvercast
setParticleCircle
setParticleParams
setParticleRandom
setPlayable
setPlayerRespawnTime
setPos
setPosASL
setPosASL2
setPosATL
setPosition
setRadioMsg
setRain
setRank
setRectangular
setRepairCargo
setSide
setSimpleTaskDescription
setSimpleTaskDestination
setSimpleTaskTarget
setSize
setSoundEffect
setSpeedMode
setTargetAge
setTaskResult
setTaskState
setTerrainGrid
setText
setTitleEffect
setTriggerActivation
setTriggerArea
setTriggerStatements
setTriggerText
setTriggerTimeout
setTriggerType
setType
setUnconscious
setUnitAbility
setUnitPos
setUnitPosWeak
setUnitRank
setVariable
setVectorDir
setVectorDirAndUp
setVectorUp
setVehicleAmmo
setVehicleArmor
setVehicleId
setVehicleInit
setVehicleLock
setVehiclePosition
setVehicleTiPars
setVehicleVarName
setVelocity
setVelocityTransformation
setViewDistance
setVisibleIfTreeCollapsed
setWaypointBehaviour
setWaypointCombatMode
setWaypointCompletionRadius
setWaypointDescription
setWaypointFormation
setWaypointHousePosition
setWaypointPosition
setWaypointScript
setWaypointSpeed
setWaypointStatements
setWaypointTimeout
setWaypointType
setWaypointVisible
setWind
setWPPos
show3DIcons
showCinemaBorder
showCommandingMenu
showCompass
showGPS
showHUD
showLegend
showMap
shownCompass
showNewEditorObject
shownGPS
shownMap
shownPad
shownRadio
shownWarrant
shownWatch
showPad
showRadio
showSubtitles
showWarrant
showWatch
showWaypoint
side
side location
sideChat
sideEnemy
sideFriendly
sideLogic
sideRadio
sideUnknown
simpleTasks
simulationEnabled
sin
size
sizeOf
skill
skill vehicle
skipTime
sleep
sliderPosition
sliderRange
sliderSetPosition
sliderSetRange
sliderSetSpeed
sliderSpeed
someAmmo
soundVolume
spawn
speed
speedMode
sqrt
startLoadingScreen
step
stop
stopped
str
supportInfo
suppressFor
surfaceIsWater
surfaceType
switch
switch do
switchableUnits
switchAction
switchCamera
switchGesture
switchLight
switchMove
synchronizedObjects
synchronizeObjectsAdd
synchronizeObjectsRemove
synchronizeWaypoint
synchronizeWaypoint trigger

tan
targetsAggregate
targetsQuery
taskChildren
taskCompleted
taskDescription
taskDestination
taskHint
taskNull
taskParent
taskResult
taskState
teamMember
teamMemberNull
teamName
teams
teamSwitch
teamSwitchEnabled
teamType
terminate
text
text location
textLog
textLogFormat
tg
then
throw
time
titleCut
titleFadeOut
titleObj
titleRsc
titleText
to
toArray
toLower
toString
toUpper
triggerActivated
triggerActivation
triggerArea
triggerAttachedVehicle
triggerAttachObject
triggerAttachVehicle
triggerStatements
triggerText
triggerTimeout
triggerType
true
try
turretUnit
type
typeName
typeOf

uiNamespace
uisleep
unassignTeam
unassignVehicle
unitBackpack
unitPos
unitReady
unitsBelowHeight
units
unlockAchievement
unregisterTask
updateDrawIcon
updateMenuItem
updateObjectTree
useAudioTimeForMoves

vectorDir
vectorUp
vehicle
vehicleChat
vehicleRadio
vehicles
vehicleVarName
velocity
verifySignature
viewDistance
visibleMap

waitUntil
waypointAttachedObject
waypointAttachedVehicle
waypointAttachObject
waypointAttachVehicle
waypointBehaviour
waypointCombatMode
waypointCompletionRadius
waypointDescription
waypointFormation
waypointHousePosition
waypointPosition
waypoints
waypointScript
waypointShow
waypointSpeed
waypointStatements
waypointTimeout
waypointType
waypointVisible
weaponDirection
weapons
weaponsTurret
west
WFSideText
while
wind
with
worldName
worldToModel
worldToScreen
";
    }
}